apiVersion: apps/v1
kind: Deployment
metadata:
  name: woohu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: woohu
  template:
    metadata:
      labels:
        app: woohu
    spec:
      containers:
      - image: okteto.dev/woohu:latest
        name: woohu
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "87d1f08a-61b5-4cba-9f1a-126f86ced63f"
        - name: Vless_Path
          value: "/sfrgefef324"
        - name: Vmess_UUID
          value: "87d1f08a-61b5-4cba-9f1a-126f86ced63f"
        - name: Vmess_Path
          value: "/dhtfgrfe74656"
        - name: Share_Path
          value: "/v2link"
